# Generated by Django 4.0.3 on 2022-05-14 16:30

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Informe um usuário válido.Este valor deve conter apenas letras e números e os caracteres @/./+/-/_.', 'invalid')], verbose_name='Usuário')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuário')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonimo')),
                ('is_trusty', models.BooleanField(default=False, verbose_name='E-Mail confirmado')),
                ('tipo', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='F', max_length=1, verbose_name='Tipo')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('data_nascimento', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Nenhuma das opções')], default='N', max_length=1, null=True, verbose_name='Sexo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de cadastro')),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data da ultima modificação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('imagem_destaque', models.ImageField(blank=True, max_length=250, null=True, upload_to='produto/categoria/', verbose_name='Imagem de destaque')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'produto_categoria',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidade',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=2000, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('altura', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('largura', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('comprimento', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('padrao', models.BooleanField(default=False)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cidade', verbose_name='Cidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço do usuário',
                'verbose_name_plural': 'Endereços dos usuários',
                'db_table': 'usuario_endereco',
            },
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('padrao', models.BooleanField(default=False)),
                ('imagem', models.ImageField(max_length=255, upload_to='produto/produto')),
                ('alt', models.CharField(blank=True, default='Imagem de produto', max_length=150, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens dos produtos',
                'db_table': 'produto_imagem',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
                ('pais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pais')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estado'),
        ),
    ]
